repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff .
        language: system
        types:
          - python

      - id: black
        name: black
        entry: poetry run black .
        language: system
        types:
          - python
